#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_Name]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo ctr container rm ${name}
ctr container rm ${name}
