#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [PV_NAME]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo kubectl delete pv "${name}"
kubectl delete pv "${name}"
