#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [SVC_NAME]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo minikube service "${name}" --url
minikube service "${name}" --url
