#!/bin/bash
# List All Containers in a Pod in Kubernetes Cluster
# refer to https://discuss.devopscube.com/t/how-to-list-all-containers-in-a-pod-in-kubernetes-cluster/429
echo 'kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | xargs -n1 | sort'
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | xargs -n1 | sort
