#!/bin/bash
# List All Containers in a Pod in Kubernetes Cluster
# refer to https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/
echo 'kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | xargs -n1 | sort'
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | xargs -n1 | sort
