#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Deployment_Name]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo kubectl delete deployment ${name}
kubectl delete deployment ${name}
