#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [DEPLOYMENT_NAME]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo kubectl describe deployment "${name}"
kubectl describe deployment "${name}"
