#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [INGRESS_NAME]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo kubectl delete ingress "${name}"
kubectl delete ingress "${name}"
