#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [POD_Name]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo kubectl delete pods "${name}"
kubectl delete pods "${name}"

rc=$?
#echo ${rc}
if [ $rc -gt 0 ]; then
    echo
    #echo kubectl get pods -A --no-headers
    #kubectl get pods -A --no-headers
    ns=$(kubectl get pods -A --no-headers | grep ${name} | awk '{print $1}')
    #echo namespace is ${ns}
    if [ ! -z "${ns}" ]; then
        echo kubectl delete pods ${name} -n ${ns}
        kubectl delete pods ${name} -n ${ns}
    fi
fi
