#!/bin/bash
if [ -z "${1}" ]; then
    sec=1
else
    sec=${1}
fi

while :
do
    date '+%Y-%m-%d %H:%M:%S'
    echo kubectl get pod -A --sort-by=.metadata.namespace
    kubectl get pod -A --sort-by=.metadata.namespace
    echo
    sleep $sec
done

