#!/bin/bash
if [ -z "${1}" ]; then
    echo kubectl get svc -A
    kubectl get svc -A
    exit
fi

name=${1}

echo kubectl describe svc ${name}
kubectl describe svc ${name}
rc=$?
#echo ${rc}
if [ $rc -gt 0 ]; then
    echo
    #echo kubectl get svc -A --no-headers
    #kubectl get svc -A --no-headers
    ns=$(kubectl get svc -A --no-headers | grep ${name} | awk '{print $1}')
    #echo namespace is ${ns}
    if [ ! -z "${ns}" ]; then
        echo kubectl describe svc ${name} -n ${ns}
        kubectl describe svc ${name} -n ${ns}
    fi
fi
